
development:
  stripe_secret_key: 'sk_test_51Ko7pTKOnbxyLu1StV0t1Sga4F7ImBpuLIOqnma1SehjRb2zBNMOdunjeivOfcCauqDZFc4eaWsGnC76dZzG2xe400SwpQ5UEp'
  stripe_publishable_key: 'pk_test_51Ko7pTKOnbxyLu1SdsyaXY4POFUIqZoj6Ni8Wp7TqS8urCPfpLQ3hMgNWcZEeCvcn7P3OZxOao08apPiZCdqLMCL00cLU5t3KH'
